### ISSUE TITLE
社区版网站不支持Edge  Chromium版浏览器

### ISSUE THREAD

**Issue by Curtion** [feisuanyz/SoFlu-adp#13]
![QQ截图20210506102408](https://user-images.githubusercontent.com/14846890/117233547-e60d0c00-ae55-11eb-891c-6748fa82d472.png)
![QQ截图20210506102751](https://user-images.githubusercontent.com/14846890/117233549-e73e3900-ae55-11eb-8e90-d8dcefceaa55.png)

**Comment by feisuanyz** [comment]
您好，目前暂时不支持Edge Chromium浏览器，请尝试使用以下浏览器，谢谢~~
![图片](https://user-images.githubusercontent.com/79617492/117909149-498eb200-b30c-11eb-8603-1a0fca87b2bf.png)

**Comment by Curtion** [comment]
我就是在反馈你们居然会拒绝支持一个现代浏览器，谢谢你的回应
