### ISSUE TITLE
我调用Java一些系统函数我怎么调用啊？比如获取系统时间什么的，当做一个参数写入数据库

### ISSUE THREAD

**Issue by sherryleeli** [feisuanyz/SoFlu-adp#4]
如题。

**Comment by feisuanyz** [comment]
1，在项目加载项添加函数依赖包，选择最新版本添加
2，在可视化视图窗体页面，拖拉一个函数组件
3，填写调用函数类型（选择**自定义函数**）、函数类的路径（选择**DateFunction函数**默认路径是**com.feisuanyz.flow.DateFunction**）、函数名（获取系统时间选择**getSysTime()**）
