### ISSUE TITLE
我在实体模型配置了参数，通过赋值组件赋值给SQL的时候，使用测试用例填写了一些案例数据，无法写入数据库

### ISSUE THREAD

**Issue by huhu115** [feisuanyz/SoFlu-adp#5]
FYI.

**Comment by feisuanyz** [comment]
请您截图出来我们这边看看可以么？

**Comment by huhu115** [comment]
![Uploading 9DC2A675-4F9B-4173-964B-AAC07578BBD9.jpeg…]()

**Comment by huhu115** [comment]
![6EE5A0CF-961F-4BEA-A54F-C4D67481E918](https://user-images.githubusercontent.com/26320322/114118533-89ccd000-991b-11eb-8eec-e36c380e68b7.jpeg)

**Comment by huhu115** [comment]
![2CECE3D0-7BDB-4E28-9730-7F09DE246EF2](https://user-images.githubusercontent.com/26320322/114118829-18415180-991c-11eb-9c6e-8a0d38b9bd7b.jpeg)

**Comment by feisuanyz** [comment]
您的问题如下：数据模型字段需要和您写的SQL语句的VALUES保持不一致导致的。
![图片](https://user-images.githubusercontent.com/79617492/114122070-1e3a3100-9922-11eb-8bd0-61fd3541c6fb.png)
![图片](https://user-images.githubusercontent.com/79617492/114122126-3316c480-9922-11eb-9d48-eb569ddb9507.png)

数据模型字段需要和您写的SQL语句的VALUES保持一致，您这边需要修改一下，再重新验证一下，谢谢~~

**Comment by huhu115** [comment]
模型字段与SQL的value修改了，数据插入成功了，感谢~

**Comment by feisuanyz** [comment]
ok，后续如果再遇到问题，欢迎及时反馈，感谢您使用SoFlu全自动开发平台~~
