### ISSUE TITLE
停掉模块是否是执行shutdown.sh 脚本，如果apps下有多个部署包，能否指定停掉特定的部署服务,还是只能全量停掉所有服务

### ISSUE THREAD

**Issue by bluecoding** [feisuanyz/SoFlu-adp#7]
停掉模块是否是执行shutdown.sh 脚本，如果apps下有多个部署包，能否指定停掉特定的部署服务,还是只能全量停掉所有服务

**Comment by feisuanyz** [comment]
如果一个执行引擎部署多个部署包，执行shutdown.sh 脚本停止服务时，都全部停止所有部署包，如果不想停掉某一个服务，则需要单独部署。
