### ISSUE TITLE
请问测试用例这里要怎么操作？我这里看不到执行的按钮

### ISSUE THREAD

**Issue by 540240126** [feisuanyz/SoFlu-adp#9]
fyi

**Comment by feisuanyz** [comment]
社区版的SoFlu全自动开发平台提供创建测试用例功能，但是执行测试用例时，您需要安装本地客户端后，才能执行测试的操作功能。
具体操作详情，请参见飞SoFlu全自动开发平台官网文档中心（全自动开发平台 / 快速入门 / 1本地客户端 / 1.3 安装本地客户端）
文档中心地址：https://www.feisuanyz.com/support/helpCenter
